production:
  adapter: mysql
  database: ublip_prod
  username: root
  password: t8eyAtRe
  host: localhost
development:
  adapter: mysql
  database: ublip_v2_development
  username: ublip_dev
  password: ublip_dev
  socket: /tmp/mysql.sock
